name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run-unit-tests:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: macOS
      run: make ci-macos
  check-dist:
    needs: build-and-run-unit-tests
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: SwiftPM
      run: make ci-swiftpm
